[project]
name = "car-value"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "fastexcel>=0.14.0",
    "polars>=1.31.0",
    "pydantic>=2.11.7",
    "xlsxwriter>=3.2.5",
]
